title: Services
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: template
        field:
          hide_partials: true
          blueprint: false
          display: Template
          type: template
          icon: template
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: layout
        field:
          hide_partials: true
          blueprint: false
          display: Layout
          type: template
          icon: template
          listable: hidden
          instructions_position: above
          visibility: visible
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
  content_side:
    display: 'Content side'
    fields:
      -
        handle: hero_headline
        field:
          input_type: text
          antlers: false
          display: 'Hero headline'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: hero_tag
        field:
          input_type: text
          antlers: false
          display: 'Hero tag'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: hero_bg
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'Hero bg'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          max_files: 1
      -
        handle: services_content
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: 'services content'
          type: markdown
          icon: markdown
          listable: hidden
          instructions_position: above
          visibility: visible
