title: Services
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: template
        field:
          hide_partials: true
          blueprint: false
          display: Template
          type: template
          icon: template
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: layout
        field:
          hide_partials: true
          blueprint: false
          display: Layout
          type: template
          icon: template
          listable: hidden
          instructions_position: above
          visibility: visible
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
  content_side:
    display: 'Content side'
    fields:
      -
        handle: hero_headline
        field:
          input_type: text
          antlers: false
          display: 'Hero headline'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: hero_tag
        field:
          input_type: text
          antlers: false
          display: 'Hero tag'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: hero_bg
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'Hero bg'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          max_files: 1
      -
        handle: services_content
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: 'services content'
          type: markdown
          icon: markdown
          listable: hidden
          instructions_position: above
          visibility: visible
  all_services:
    display: 'All services'
    fields:
      -
        handle: services_tabs
        field:
          collapse: false
          previews: true
          sets:
            service_tab:
              display: 'service tab'
              fields:
                -
                  handle: title
                  field:
                    input_type: text
                    antlers: false
                    display: Title
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: link
                  field:
                    display: Link
                    type: link
                    icon: link
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: has_tag
                  field:
                    default: false
                    display: 'Has tag'
                    type: toggle
                    icon: toggle
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: tag_text
                  field:
                    input_type: text
                    antlers: false
                    display: 'Tag text'
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    if:
                      has_tag: 'equals true'
          display: 'Services tabs'
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: services_list
        field:
          collapse: false
          previews: true
          sets:
            service:
              display: Service
              fields:
                -
                  handle: title
                  field:
                    input_type: text
                    antlers: false
                    display: Title
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: id_for_link
                  field:
                    input_type: text
                    antlers: false
                    display: 'Id for link'
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: description
                  field:
                    antlers: false
                    display: Description
                    type: textarea
                    icon: textarea
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: content_list
                  field:
                    collapse: false
                    previews: true
                    sets:
                      content_item:
                        display: 'Content item'
                        fields:
                          -
                            handle: content
                            field:
                              antlers: false
                              display: Content
                              type: textarea
                              icon: textarea
                              listable: hidden
                              instructions_position: above
                              visibility: visible
                    display: 'Content list'
                    type: replicator
                    icon: replicator
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: image_banner
                  field:
                    mode: list
                    container: assets
                    restrict: false
                    allow_uploads: true
                    show_filename: true
                    max_files: 1
                    display: 'Image banner'
                    type: assets
                    icon: assets
                    listable: hidden
                    instructions_position: above
                    visibility: visible
          display: 'Services list'
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
          visibility: visible
  prices:
    display: Prices
    fields:
      -
        handle: price_description
        field:
          antlers: false
          display: 'Price description'
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: price_cards
        field:
          collapse: false
          previews: true
          sets:
            price:
              display: Price
              fields:
                -
                  handle: title
                  field:
                    input_type: text
                    antlers: false
                    display: Title
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: subtitle
                  field:
                    input_type: text
                    antlers: false
                    display: Subtitle
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: price
                  field:
                    input_type: text
                    antlers: false
                    display: Price
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: price_additional_info
                  field:
                    input_type: text
                    antlers: false
                    display: 'Price additional info'
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: description
                  field:
                    antlers: false
                    display: Description
                    type: textarea
                    icon: textarea
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: price_options
                  field:
                    display: 'Price options'
                    type: list
                    icon: list
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: is_primary
                  field:
                    default: false
                    display: 'Is primary'
                    type: toggle
                    icon: toggle
                    listable: hidden
                    instructions_position: above
                    visibility: visible
          display: 'Price cards'
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
          visibility: visible
